services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=potion_crafters'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'
